"""
pdf_export.py
-------------
Generate clean, professionally formatted PDFs for:
  - Cover letters
  - Resume analysis reports
  - Full Apply Package (ATS + cover letter + bullets + thank-you)
  - Any writing suite output

Returns bytes so Streamlit can offer a download button.
"""

import io
import re
from datetime import date
from fpdf import FPDF

# ── Colors (RGB) ──────────────────────────────────────────────────
NAVY   = (15,  23,  42)   # #0f172a
BLUE   = (37,  99, 235)   # #2563eb
SLATE  = (71,  85, 105)   # #475569
LIGHT  = (241, 245, 249)  # #f1f5f9
WHITE  = (255, 255, 255)
GREEN  = (5,  150,  105)  # #059669
AMBER  = (217, 119,   6)  # #d97706
RED    = (220,  38,  38)  # #dc2626


_CHAR_MAP = {
    "\u2014": "-", "\u2013": "-",   # em/en dash -> hyphen
    "\u2192": "->",                  # rightwards arrow
    "\u2190": "<-",                  # leftwards arrow
    "\u2022": "-",                   # bullet
    "\u26a0": "[!]",                 # warning sign
    "\u2018": "'", "\u2019": "'",   # smart single quotes
    "\u201c": '"', "\u201d": '"',   # smart double quotes
    "\u2026": "...",                 # ellipsis
    "\u00b7": "-",                   # middle dot
    "\u2713": "OK", "\u2714": "OK", # check marks
    "\u2717": "X", "\u2718": "X",   # cross marks
    "\u00ae": "(R)", "\u2122": "(TM)",
    "\u2665": "<3", "\u2764": "<3",
    "\u00a0": " ",                   # non-breaking space
}

def _safe(text):
    """Convert text to latin-1 safe string for fpdf Helvetica core font."""
    for char, replacement in _CHAR_MAP.items():
        text = text.replace(char, replacement)
    # Encode any remaining out-of-range characters
    return text.encode("latin-1", errors="ignore").decode("latin-1")


def _strip_md(text):
    """Remove markdown and non-latin-1 characters for plain PDF rendering."""
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
    text = re.sub(r"\*(.*?)\*",     r"\1", text)
    text = re.sub(r"#{1,6}\s*",     "",    text)
    text = re.sub(r"`(.*?)`",       r"\1", text)
    return _safe(text.strip())


class CareerPDF(FPDF):
    """Base PDF class with CareerIQ branding."""

    def __init__(self):
        super().__init__()
        self.set_margins(22, 22, 22)
        self.set_auto_page_break(auto=True, margin=22)

    def normalize_text(self, text):
        """Auto-sanitize any string to latin-1 before rendering."""
        return _safe(str(text))

    def header(self):
        # Thin navy top bar
        self.set_fill_color(*NAVY)
        self.rect(0, 0, 210, 7, "F")
        # Logo text in bar
        self.set_xy(22, 1)
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*WHITE)
        self.cell(0, 5, "CareerIQ", ln=False)
        self.set_text_color(*SLATE)
        self.ln(10)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "", 7.5)
        self.set_text_color(*SLATE)
        self.cell(0, 5, f"Generated by CareerIQ  ·  careeriq.local  ·  {date.today().strftime('%B %d, %Y')}",
                  align="C")

    def section_header(self, title, color=BLUE):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*color)
        self.set_fill_color(*LIGHT)
        self.cell(0, 7, title.upper(), ln=True, fill=True)
        self.ln(1)
        self.set_text_color(*NAVY)

    def divider(self):
        self.set_draw_color(*LIGHT)
        y = self.get_y()
        self.line(22, y, 188, y)
        self.ln(4)

    def body_text(self, text, size=10.5):
        self.set_font("Helvetica", "", size)
        self.set_text_color(*NAVY)
        clean = _strip_md(text)
        # Handle bullet lines
        for line in clean.split("\n"):
            line = line.strip()
            if not line:
                self.ln(3)
                continue
            if line.startswith(("•", "-", "*")):
                self.set_x(26)
                self.set_font("Helvetica", "", 9)
                self.set_text_color(*SLATE)
                self.cell(4, 5, "•", ln=False)
                self.set_x(30)
                self.set_font("Helvetica", "", size)
                self.set_text_color(*NAVY)
                self.multi_cell(0, 5.5, line.lstrip("•-* "), ln=True)
            else:
                self.multi_cell(0, 5.5, line, ln=True)
        self.ln(1)

    def score_box(self, score, grade, label="Resume Score"):
        color = GREEN if score >= 75 else (AMBER if score >= 50 else RED)
        # Box
        self.set_fill_color(*color)
        x, y = self.get_x(), self.get_y()
        self.rect(x, y, 28, 22, "F")
        # Score number
        self.set_xy(x, y + 3)
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(*WHITE)
        self.cell(28, 8, str(score), align="C", ln=False)
        # Grade
        self.set_xy(x, y + 11)
        self.set_font("Helvetica", "B", 9)
        self.cell(28, 6, grade, align="C", ln=False)
        # Label
        self.set_xy(x + 32, y + 4)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*NAVY)
        self.cell(0, 6, label, ln=True)
        self.set_xy(x + 32, y + 10)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*SLATE)
        self.cell(0, 5, f"Grade {grade}  ·  {score}/100", ln=True)
        self.set_y(y + 26)
        self.set_text_color(*NAVY)

    def progress_row(self, label, score):
        color = GREEN if score >= 75 else (AMBER if score >= 50 else RED)
        self.set_font("Helvetica", "", 9.5)
        self.set_text_color(*NAVY)
        self.cell(48, 5.5, label, ln=False)
        # Bar background
        bx, by = self.get_x(), self.get_y()
        self.set_fill_color(241, 245, 249)
        self.rect(bx, by + 1, 80, 3, "F")
        # Bar fill
        self.set_fill_color(*color)
        self.rect(bx, by + 1, 80 * score / 100, 3, "F")
        # Score text
        self.set_x(bx + 84)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*color)
        self.cell(20, 5.5, f"{score}%", ln=True)
        self.set_text_color(*NAVY)
        self.ln(1)

    def chip_row(self, label, keywords, color=BLUE):
        if not keywords:
            return
        self.set_font("Helvetica", "B", 8.5)
        self.set_text_color(*SLATE)
        self.cell(0, 5, label, ln=True)
        self.set_font("Helvetica", "", 8.5)
        self.set_text_color(*color)
        text = "  ·  ".join(keywords)
        self.multi_cell(0, 5, text, ln=True)
        self.ln(2)
        self.set_text_color(*NAVY)


# ── Cover Letter ──────────────────────────────────────────────────

def cover_letter_pdf(text, name, company, role):
    """
    text   : plain text of the cover letter
    name   : applicant name
    company: target company
    role   : target role
    Returns: bytes
    """
    pdf = CareerPDF()
    pdf.add_page()

    # Title block
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 9, "Cover Letter", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*SLATE)
    pdf.cell(0, 5.5, f"{name}  ·  {role} at {company}", ln=True)
    pdf.ln(4)
    pdf.divider()

    pdf.body_text(text, size=10.5)

    return bytes(pdf.output())


# ── Resume Analysis Report ────────────────────────────────────────

def analysis_report_pdf(profile, analysis):
    """
    profile  : parse_resume() dict
    analysis : full_analysis() dict
    Returns  : bytes
    """
    pdf = CareerPDF()
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 9, "Resume Analysis Report", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*SLATE)
    pdf.cell(0, 5.5, f"{profile.get('name','Candidate')}  ·  Generated {date.today().strftime('%B %d, %Y')}", ln=True)
    pdf.ln(4)
    pdf.divider()

    # Overall score
    pdf.score_box(analysis["overall_score"], analysis["grade"])
    pdf.ln(4)

    # Section breakdown
    pdf.section_header("Section Scores")
    for sec_name, sec_data in analysis["section_analyses"].items():
        pdf.progress_row(sec_name, sec_data["score"])
        for issue in sec_data.get("issues", [])[:2]:
            pdf.set_font("Helvetica", "", 8.5)
            pdf.set_text_color(*RED)
            pdf.set_x(26)
            pdf.cell(0, 4.5, f"[!] {_strip_md(issue)}", ln=True)
        for sug in sec_data.get("suggestions", [])[:1]:
            pdf.set_font("Helvetica", "", 8.5)
            pdf.set_text_color(*BLUE)
            pdf.set_x(26)
            pdf.cell(0, 4.5, f"-> {_strip_md(sug)}", ln=True)
        pdf.set_text_color(*NAVY)
        pdf.ln(1)

    # Missing sections
    if analysis.get("missing_sections"):
        pdf.ln(2)
        pdf.section_header("Missing Sections", color=RED)
        for sec in analysis["missing_sections"]:
            tip = analysis.get("missing_tips", {}).get(sec, "")
            pdf.set_font("Helvetica", "B", 9.5)
            pdf.set_text_color(*RED)
            pdf.cell(0, 5.5, f"No {sec} section", ln=True)
            if tip:
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(*SLATE)
                pdf.multi_cell(0, 5, _strip_md(tip), ln=True)
            pdf.ln(1)
        pdf.set_text_color(*NAVY)

    # Bullet coach
    bullets = analysis.get("bullet_analyses", [])
    weak = [b for b in bullets if b["score"] < 75]
    if weak:
        pdf.add_page()
        pdf.section_header("Bullet Coach — Needs Improvement")
        for b in sorted(weak, key=lambda x: x["score"])[:10]:
            color = GREEN if b["score"] >= 75 else (AMBER if b["score"] >= 50 else RED)
            pdf.set_fill_color(*color)
            pdf.set_font("Helvetica", "B", 8.5)
            pdf.set_text_color(*WHITE)
            pdf.cell(22, 5.5, f"  {b['score']}%", fill=True, ln=False)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(*NAVY)
            pdf.set_x(pdf.get_x() + 3)
            pdf.multi_cell(0, 5.5, _strip_md(b["text"]), ln=True)
            for issue in b.get("issues", []):
                pdf.set_x(26)
                pdf.set_font("Helvetica", "", 8.5)
                pdf.set_text_color(*RED)
                pdf.cell(0, 4.5, f"[!] {_strip_md(issue)}", ln=True)
            if b.get("suggestion"):
                pdf.set_x(26)
                pdf.set_font("Helvetica", "I", 8.5)
                pdf.set_text_color(*BLUE)
                pdf.multi_cell(0, 4.5, f"-> {_strip_md(b['suggestion'])}", ln=True)
            pdf.set_text_color(*NAVY)
            pdf.ln(3)

    # Skills
    skills = profile.get("skills", [])
    if skills:
        pdf.ln(2)
        pdf.section_header("Detected Skills")
        pdf.chip_row("", skills, color=BLUE)

    return bytes(pdf.output())


# ── Apply Package ─────────────────────────────────────────────────

def apply_package_pdf(name, job, ats, cover_letter_text, bullets_text, thankyou_text):
    """
    Full application package PDF.
    name             : applicant name
    job              : job dict {title, company, location}
    ats              : ats_scan() result or None
    cover_letter_text: string
    bullets_text     : string
    thankyou_text    : string
    Returns          : bytes
    """
    pdf = CareerPDF()
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 10, "Apply Package", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*SLATE)
    role_line = f"{job.get('title','Role')} at {job.get('company','Company')}"
    if job.get("location"):
        role_line += f"  ·  {job['location']}"
    pdf.cell(0, 5.5, role_line, ln=True)
    pdf.cell(0, 5, f"Prepared for: {name}  ·  {date.today().strftime('%B %d, %Y')}", ln=True)
    pdf.ln(4)
    pdf.divider()

    # ATS Score
    if ats:
        pdf.section_header("ATS Compatibility Score")
        color = GREEN if ats["verdict"][0] == "strong" else (AMBER if ats["verdict"][0] == "medium" else RED)
        pdf.score_box(ats["score"], ats["verdict"][0].upper()[:1], label="ATS Score")
        pdf.set_font("Helvetica", "", 9.5)
        pdf.set_text_color(*color)
        pdf.cell(0, 5, _strip_md(ats["verdict"][1]), ln=True)
        pdf.ln(2)
        pdf.chip_row("Keywords matched:", ats.get("found_keywords", [])[:8], color=GREEN)
        pdf.chip_row("Keywords missing:", ats.get("missing_keywords", [])[:8], color=RED)
        pdf.divider()

    # Targeted bullets
    if bullets_text and bullets_text.strip():
        pdf.section_header("Targeted Resume Bullets")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*SLATE)
        pdf.cell(0, 5, "Add these bullets to your resume to address skill gaps for this role:", ln=True)
        pdf.ln(1)
        pdf.body_text(bullets_text, size=9.5)
        pdf.divider()

    # Cover letter
    if cover_letter_text and cover_letter_text.strip():
        pdf.add_page()
        pdf.section_header("Cover Letter")
        pdf.body_text(cover_letter_text, size=10.5)
        pdf.divider()

    # Thank-you email
    if thankyou_text and thankyou_text.strip():
        pdf.section_header("Thank-You Email")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*SLATE)
        pdf.cell(0, 5, "Send within 24 hours of your interview:", ln=True)
        pdf.ln(1)
        pdf.body_text(thankyou_text, size=10.5)

    return bytes(pdf.output())


# ── Generic writing output ────────────────────────────────────────

def writing_output_pdf(title, body, name="", job_title="", company=""):
    """
    Generic PDF for any Writing Suite output.
    """
    pdf = CareerPDF()
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 9, title, ln=True)
    if name or company:
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*SLATE)
        meta = "  ·  ".join(x for x in [name, job_title, company] if x)
        pdf.cell(0, 5.5, meta, ln=True)
    pdf.ln(4)
    pdf.divider()
    pdf.body_text(body, size=10.5)

    return bytes(pdf.output())


# ── Interview Question Bank PDF ───────────────────────────────────

def interview_pdf(questions: list, job_title: str = "", company: str = "", name: str = ""):
    """
    questions: list of {question, hint, type} dicts from generate_interview_questions()
    Returns: bytes
    """
    pdf = CareerPDF()
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 9, "Interview Question Bank", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*SLATE)
    meta = "  ·  ".join(x for x in [name, job_title, company] if x)
    if meta:
        pdf.cell(0, 5.5, meta, ln=True)
    pdf.ln(4)
    pdf.divider()

    type_colors = {
        "Technical":     BLUE,
        "Role-Specific": (139, 92, 246),
        "Behavioral":    GREEN,
        "Situational":   AMBER,
        "Closing":       SLATE,
    }
    type_order = ["Technical", "Role-Specific", "Behavioral", "Situational", "Closing"]
    grouped: dict = {}
    for q in questions:
        t = q.get("type", "General")
        grouped.setdefault(t, []).append(q)

    for qtype in type_order + [k for k in grouped if k not in type_order]:
        if qtype not in grouped:
            continue
        color = type_colors.get(qtype, SLATE)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*color)
        pdf.cell(0, 6, f"-- {qtype.upper()} --", ln=True)
        pdf.ln(1)

        for item in grouped[qtype]:
            q_text = _safe(item.get("question", ""))
            hint   = _safe(item.get("hint", ""))

            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*NAVY)
            pdf.multi_cell(0, 5.5, q_text, ln=True)

            if hint:
                pdf.set_font("Helvetica", "I", 9)
                pdf.set_text_color(*SLATE)
                pdf.set_x(26)
                pdf.multi_cell(0, 5, f"Tip: {hint}", ln=True)

            # Answer space lines
            pdf.set_draw_color(220, 220, 220)
            for _ in range(3):
                y = pdf.get_y() + 2
                pdf.line(22, y, 188, y)
                pdf.ln(5)
            pdf.ln(3)

    return bytes(pdf.output())


# ── STAR Stories PDF ──────────────────────────────────────────────

def star_stories_pdf(stories: list, name: str = ""):
    """
    stories: list of {title, situation, task, action, result} dicts
    Returns: bytes
    """
    pdf = CareerPDF()
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 9, "STAR Story Bank", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*SLATE)
    sub = "  ·  ".join(x for x in [name, f"{len(stories)} stories"] if x)
    pdf.cell(0, 5.5, sub, ln=True)
    pdf.ln(4)
    pdf.divider()

    label_colors = {
        "Situation": BLUE,
        "Task":      (139, 92, 246),
        "Action":    GREEN,
        "Result":    AMBER,
    }

    for i, story in enumerate(stories, 1):
        # Story title bar
        pdf.set_fill_color(*NAVY)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*WHITE)
        pdf.cell(0, 7, f"  {i}. {_safe(story.get('title', 'Story'))}", fill=True, ln=True)
        pdf.ln(2)

        for label in ("Situation", "Task", "Action", "Result"):
            text = _safe(story.get(label.lower(), "") or "")
            if not text:
                continue
            color = label_colors[label]
            pdf.set_font("Helvetica", "B", 8.5)
            pdf.set_text_color(*color)
            pdf.cell(20, 5, label.upper(), ln=False)
            pdf.set_font("Helvetica", "", 9.5)
            pdf.set_text_color(*NAVY)
            pdf.multi_cell(0, 5, text, ln=True)
            pdf.ln(1)

        if i < len(stories):
            pdf.divider()

    return bytes(pdf.output())
